name: Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - docs/**

jobs:
  build:
    runs-on: ubuntu-20.04

    env:
      GO_VERSION: 1.16.x

    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - uses: actions/checkout@v2

      - id: build
        name: Build
        run: |
          VERSION="$(echo ${{ github.sha }} | cut -c 1-8)"
          echo "::set-output name=version::$VERSION"
          make VERSION="$VERSION" bin/netsoc

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: cli-amd64-${{ steps.build.outputs.version }}
          path: bin/netsoc
