name: Build

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest

    env:
      GO_VERSION: 1.15.x
      CR_PAT_USER: devplayer0
      REPO: ghcr.io/netsoc/iamd

    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - uses: actions/checkout@v2

      - name: Build
        run: make VERSION="$(echo ${{ github.sha }} | cut -c 1-8)" bin/netsoc

      - name: Upload binary
        uses: actions/upload-artifact@v2
        path: bin/netsoc
